- hosts: all
  tasks:
  - name: install packages
    yum: 
      name: "{{ packages }}"
      state: present
    vars: 
      packages: 
      - wget
      - tree
      - unzip
      - httpd
      - git