- hosts: all
  become: yes
  tasks: 
  - hostname:
      name: "{{ inventory_hostname }}"
  - debug:
      msg: "{{ ansible_distribution }}"
  - name: install apache
    include_tasks: "{{ ansible_distribution }}.yml"